### ISSUE TITLE
Clarification questions

### ISSUE THREAD

**Issue by aewindle110** [micasense/imageprocessing#118]
Hi,

I was wondering if there is a difference between the terms 'unwarping' and 'undistorting'? They both remove lens distortion effects, correct? 

Also, I was wondering where the 6:1 ratio of direct to diffuse light derived from? Should I be changing this depending on the sky condition the day of my flights?

**Comment by poynting** [comment]
Yes the two terms are used interchangeably.

As far as the direct to diffuse ratio: yes, it is a general estimate for sunny skies and it will change relative to the conditions.  This is only necessary when using DLS1, as DLS2 already handles estimating the ratio internally.
