### ISSUE TITLE
Batch Processing script not converting raw to radiance values

### ISSUE THREAD

**Issue by aewindle110** [micasense/imageprocessing#127]
I am using the Batch Processing notebook with the MicaSense test data (so I didn't alter any code within notebook) and when I try to open a stack tiff using rasterio, the array seems to be DN and not radiance values. The notebook says "# Allow this code to align both radiance and reflectance images; bu excluding a definition for panelNames above, radiance images will be used" I am wondering why these values didn't convert to radiance or reflectance?

image = rasterio.open(os.path.join(outputPath, '01gjz5AqRhRcCwhYNk8P.tif'))
blue = image.read(1)
print(type(blue))
print(blue)

<class 'numpy.ndarray'>
[[2206 1761 1718 ... 3174 3320 3558]
 [2165 1844 1883 ... 3447 3344 3477]
 [2070 1698 1587 ... 3749 3572 3644]
 ...
 [2024 2093 1915 ... 1394 1367 1313]
 [1909 1842 1688 ... 1524 1438 1316]
 [1832 1634 1404 ... 1617 1477 1283]]

**Comment by volpatoo** [comment]
Hi @aewindle110 I know this topic is closed, but I am wondering if do you find the answer to this question? I also got the same results, and I don't know if this is correct or not. Please, share with us how did you figure out this issue. Thanks
