### ISSUE TITLE
About error on camera firmware.

### ISSUE THREAD

**Issue by xurong1981** [micasense/imageprocessing#13]
When I use micasense library to deal with the data captured by our RedEdge-M, but the following error occurred.
----
ValueError: Library requires images taken with camera firmware v2.1.0 or later. Upgrade your camera firmware to use this library.
----

Is there any method to solve this problem by using old version of the source ?
Or the only method is to update the camera firmware ?

**Comment by poynting** [comment]
There is no intention of having the library support older firmware, as
older firmware doesn't store all of the elements of the full radiometric
model. That version is quite old already, we recommend strongly that all
users update the firmware to the most recent version.

Justin

**Comment by xurong1981** [comment]
I see. Thank you so much for your reply.
