### ISSUE TITLE
exif tool URL has changed to https://exiftool.org/

### ISSUE THREAD

**Issue by aklink** [micasense/imageprocessing#133]
The exiftool URL
**https://www.sno.phy.queensu.ca/~phil/exiftool/**
mentioned in 
https://github.com/micasense/imageprocessing/blob/master/MicaSense%20Image%20Processing%20Setup.ipynb
is **no longer valid**!

Please update to **https://exiftool.org/**

**Comment by poynting** [comment]
Updated in commit 8ce1325fd15713c1f73cb4f2dceac120721e6961.
