### ISSUE TITLE
CondaEnvException: Pip failed

### ISSUE THREAD

**Issue by FalconMath1975** [micasense/imageprocessing#135]
At the end of executing conda env create -f micasense_conda_env.yml : 
Pip subprocess error:
  WARNING: Generating metadata for package pyexiftoolpy produced metadata for project name pyexiftool. Fix your #egg=pyexiftoolpy fragments.
ERROR: Requested pyexiftool from git+https://github.com/smarnach/pyexiftool.git#egg=pyexiftoolpy (from -r d:\Ag Imagery\condaenv.rrxe8wh6.requirements.txt (line 3)) has different name in metadata: 'PyExifTool'

failed

CondaEnvException: Pip failed

**Comment by FalconMath1975** [comment]
used code in HRRMXJ 's pull request to successfully solve issue.

**Comment by songliVT** [comment]
How do you clone from this pull request?

**Comment by poynting** [comment]
Fixed via @HRRMXJ's PR.
