### ISSUE TITLE
LWIR alignment parameters

### ISSUE THREAD

**Issue by swawa** [micasense/imageprocessing#140]
Our camera operates with the latest firmware, but setting pyramid_levels to zero results in a real bad alignment. Setting pyramid_levels to 3 is better but not good enough for pixelwise calculations e.g. as needed for NDVI calculations. 
Therefore I calibrated our Altum geometrically using OpenCV and the chessboard method. With the gained values I get better results in the alignment. For the LWIR-band the chessboard method is not possible. Can you tell me which values are used in the default alignment for the LWIR-band?
Thanks

**Comment by poynting** [comment]
Can you upload some complete captures you're having trouble with? If not here, then email support @ micasense and they can help you out.

**Comment by poynting** [comment]
Closed due to lack of response.
