### ISSUE TITLE
Is it possible to stream video from the rededge MX using gstreamer? 

### ISSUE THREAD

**Issue by m1baldwin** [micasense/imageprocessing#142]
I have a computer vision application that I would like to use the rededge MX device for. I would need to be able to access the device as a video-4-linux device, and receive raw frames from the device into my software to process the images in real time, on a linux computer.

Is this possible with the rededge MX?

**Comment by poynting** [comment]
No, but you can use the HTTP API to pull both images and jpeg thumbnails at a relatively high rate (5+Hz depending on settings) via the GigE connection on the camera. 

http://micasense.github.io/rededge-api/api/http.html

If you have further questions it's best to reach out through a ticket at support.micasense.com
