### ISSUE TITLE
Modify the library to enable use of the RP06 calibration panels

### ISSUE THREAD

**Issue by MajorTom-LT** [micasense/imageprocessing#157]
I use rededge dual data for 10 band data processing, but the reference board we use is different from the tutorial. There are the following errors. How can I modify them?

```
Item XMP:IrradianceScaleToSIUnits not found
Item XMP:IrradianceScaleToSIUnits not found
Item XMP:CalibrationPicture not found
Item XMP:Albedo not found
Item XMP:ReflectArea not found 
Item XMP:PanelSerial not found 
```
and raise error` IOError("Comment this lne and set panel_reflectance_by_band here")`

I find these parameter in` metadata.py` , but when I print these parameter,there is no IrradianceScaleToSIUnits.

This is my board.
https://sm.ms/image/TVYSoryJHMaedFg

**Comment by poynting** [comment]
Fixed by @fdarvas via https://github.com/micasense/imageprocessing/pull/158

@MajorTom-LT please let us know if this fixed your issue.
