### ISSUE TITLE
Can this code be used with images from Parrot Sequoia?

### ISSUE THREAD

**Issue by bu-ra3y** [micasense/imageprocessing#2]
Can this code be used directly or similarly with images from Sequoia?

**Comment by poynting** [comment]
Hi @bu-ra3y.  No, this code is not intended to be used for Sequoia. However, the general concepts should be applicable but you'll need to parse through the Parrot developer forums to determine the appropriate differences.  Specifically the lens distortion model and radiometric correction model will be different.
