### ISSUE TITLE
Ask for updating the software version

### ISSUE THREAD

**Issue by fuxinyang0708** [micasense/imageprocessing#205]
Hi, I have updated the software version of RedEdge3 camera from v2.0.5 to v5.1.13. But when I read the meta data of file via exiftool, it show that the version of software still is v2.0.5. I want to know why and how can I solve this question? Thanks

**Comment by sebc06** [comment]
Hi @fuxinyang0708,

This is not related to the code in this repository. Please send a mail to support.micasense@ageagle.com with your issue with log files from the camera (https://support.micasense.com/hc/en-us/articles/360038069993-Log-Files-dat-FAQs) and a sample picture.

Closing this issue.
