### ISSUE TITLE
About  mathematical expression in Atlas

### ISSUE THREAD

**Issue by s-wtnb** [micasense/imageprocessing#23]
Thanks for the reference examples of NDVI and NDRE!
I also want to know the mathematical expression of ChlorophyllMap, Weeds2 and Weeds1 as displayed in the Atlas application.
Could you teach me?

**Comment by poynting** [comment]
No, I'm sorry but that's not ultimately the point of these tutorials. There is a lot of remote sensing literature about band combinations for rendering multispectral data. If you have the tutorial running to the point of rendering NDVI and NDRE, and showing mult-band renders like CIR in the example, then creating other indices is quite straightforward following some of the other indices available in the literature.
