### ISSUE TITLE
why we cant align pic with math?

### ISSUE THREAD

**Issue by Mercuron** [micasense/imageprocessing#25]
Hello!
why we cant calculate the exact pixels count to cut images and just using numpy to join them? There was text about temperature and other factors, but is it really affect it so much?
I think we got all values, isnt it? i tried to use 100, 1000, 10000 iterations and got the same result. How can i improve alignment quality ? 
![100](https://user-images.githubusercontent.com/45468521/49260048-e2872680-f44c-11e8-9b88-2efa28025725.png)
![1000](https://user-images.githubusercontent.com/45468521/49260049-e2872680-f44c-11e8-853e-53745671294d.png)
![10000](https://user-images.githubusercontent.com/45468521/49260050-e2872680-f44c-11e8-83d4-60974ee06c56.png)
![p81130-025804](https://user-images.githubusercontent.com/45468521/49260072-f7fc5080-f44c-11e8-9bf9-a6d4b3dcc8e0.jpg)

**Comment by poynting** [comment]
Hi @Mercuron - you're in luck, we have image alignment using lots of math now in the altum-support branch.  Check out the Alignment-RigRelatives,ipynb notebook and point it to your own images.  Note, the images need to be from at least firmware version 3.4.0 or they need to have the RigRelatives tags added as described in https://support.micasense.com/hc/en-us/articles/360006368574-Modifying-older-collections-for-Pix4Dfields-support

**Comment by poynting** [comment]
Fixed in the altum-support branch via the Alignment-RigRelatives tutorial.  Closing this in preparation to merge that branch to master soon.
