### ISSUE TITLE
How can I modify the exif data of the images?

### ISSUE THREAD

**Issue by yellowpuppy** [micasense/imageprocessing#26]
I did not calibrate the Magnetometer before the filght. Now I got a Non-uniform reflectance map probably due to the wrong DLS_pose data. Now I want to replace the camera Mag dls_pose data by my UAV IMU data. I can read the dls_pose by exiftool but I have no idea how to rewrite it.  Who can help me ? Please!

**Comment by poynting** [comment]
This isn't an issue with the library, so I'm going to close this ticket. However, we've successfully changed metadata on images using the exiv2 library under linux.

http://www.exiv2.org/index.html
http://www.exiv2.org/manpage.html
