### ISSUE TITLE
pytest.py failed with pytest.approx(different with value and "+,-"...)

### ISSUE THREAD

**Issue by niaoyu** [micasense/imageprocessing#27]
Pytest failed just like this:" 3 failed, 76 passed in 22.35 seconds"

I am so confusing about the reason"pytest.approx", Please help me!

![image](https://user-images.githubusercontent.com/23436844/51318236-b1ae8f80-1a94-11e9-878a-02524fa8bd4b.png)

**Comment by poynting** [comment]
Fixed in the altum-support branch.  Closing this in preparation for merging that branch to master in the next couple of days.
