### ISSUE TITLE
detected_panel_count is always 5

### ISSUE THREAD

**Issue by loicdtx** [micasense/imageprocessing#39]
Running the following snippet on the altum branch I get 5, for a non panel capture

```python
import os
import glob

from micasense.capture import Capture

img_path = os.path.join('.','data','0000SET','000')
img_filenames = glob.glob(os.path.join(img_path, 'IMG_0001_*.tif'))

cap = Capture.from_filelist(img_filenames)
print(cap.detect_panels())
```

**Comment by poynting** [comment]
Thanks @loicdtx that was a bug and it should be fixed in the commit I just pushed to `altum-support`. Please let me know if it's still failing for you

**Comment by loicdtx** [comment]
I confirm that this works as expected now. Thanks @poynting for the quick fix.
