### ISSUE TITLE
Question on fresnel translation

### ISSUE THREAD

**Issue by Easenguard** [micasense/imageprocessing#63]
Hallo: 
I have a question regarding the fresnel transmission function in dls.py module.

In line 81, the multilayer_transmission function defines first the phi_effect to be arcsin(sin(phi)/n1). 
But when it immediately calls the function fresnel_transmission in line 82, the f2 in line 66 would then be cos(phi)/n2. Thats a bit different from the fresnel equations.

**Comment by fdarvas** [comment]
In this case we have 
f2 = sqrt(1-sin(phi_eff)**2/n2**2) which is not equal to cos(phi_eff)/n2
