### ISSUE TITLE
writing metadata back to images

### ISSUE THREAD

**Issue by moghi005** [micasense/imageprocessing#69]
Hi,
I attempted to process the images in Pix4D but I’m unable to do it.  The reason is because the images don’t have the required metadata (Rig Name, Camera Model, Band Name, etc). Pix4Dmapper has the camera and rig information in their database but since the images don’t any metadata, it doesn’t load the rig and camera parameters from the database. I created a csv file as it was described in the tutorial, but it seems it was not enough. Is there any way to copy the metadata for each image and write it back to the images after doing all of the pre-processing steps? 

My code saves stacked images and also each individual bands so we can use pix4d for further processing. 

Thanks,
Ali

**Comment by moghi005** [comment]
I followed your suggestion and saved each band separately as a tif file. I
also used the 'batch processing' code to write the metadata.However, it
didn't help. As you mentioned, I want to save metadata back to each band so
we can use pix4D.

I wonder if there is a way to copy all the metadata from each band before
the preprocessing and write it back after the preprocessing.

Thanks,
Ali



-----

Ali Moghimi <https://about.me/alimoghimi>

PhD Candidate & Graduate Research Assistant
University of Minnesota - Twin Cities
1390 Eckles Ave. Room 2, St. Paul, MN 55108

**Comment by moghi005** [comment]
Thanks for your prompt reply.

Can we process the stacked images (5 bands) with pix4d and get orthomosaic?
My pipeline also saves stacked images in a separate folder. I only need to
save individual bands for pix4d processing. If pix4d can do orthomosaic
with stacked images, we may want to skip saving the individual images, am I
right?

The stacked images have been already aligned and converted to reflectance.
If we use reflectance map workflow, does pix4d try to convert them again to
reflectance using panel reflectance value entered by user? Since we already
converted to radiance and then reflectance, we don't want pix4d do it again.

Regarding the  filenames, should filenames (image path + image name) be
saved as the first column in the csv file (as it is in the batch processing
code)? I saved them as the last column (attached is an example of my csv
files).



-----

Ali Moghimi <https://about.me/alimoghimi>

PhD Candidate & Graduate Research Assistant
University of Minnesota - Twin Cities
1390 Eckles Ave. Room 2, St. Paul, MN 55108

**Comment by moghi005** [comment]
I'll look into that.

Is there a way to save stack files as geotiff rather than tiff?

Thanks,
Ali



-----

Ali Moghimi <https://about.me/alimoghimi>

PhD Candidate & Graduate Research Assistant
University of Minnesota - Twin Cities
1390 Eckles Ave. Room 2, St. Paul, MN 55108

**Comment by Matesanz** [comment]
If it helps anyone that was my **solution** :smile: :

```
import os
from pathlib import Path

def transfer_metadata(from_path: str, to_path: str) -> None:
    """
    Transfer metadata from one file to another
    Args:
        from_path (str): file path to extract the metadata from
        to_path (str): file path to inject metadata to
    """
    if Path(from_path).exists() and Path(to_path).exists():
        cmd = 'exiftool -TagsFromFile {} {}'.format(from_path, to_path)
        os.system(cmd)
```
