### ISSUE TITLE
exposure time clamping

### ISSUE THREAD

**Issue by fdarvas** [micasense/imageprocessing#70]
lines 178-182 in metadata.py

def exposure(self):
        exp = self.get_item('EXIF:ExposureTime')
        if math.fabs(exp-(1.0/6329.0)) < 0.0001:
            exp = 0.000274
        return exp

This test for exposure time = 1/6329 needs a tighter limit, as it returns exp = 0.000274 for low exposure times, e.g. 1/8893 s

**Comment by poynting** [comment]
Fixed via https://github.com/micasense/imageprocessing/pull/71
