### ISSUE TITLE
Aligning nearby (low altitude / short distance) images

### ISSUE THREAD

**Issue by anishau** [micasense/imageprocessing#72]
We're trying to align some images from 10 ft up with a rock or few in them - nothing very repetitive, but the alignment tools provided do not seem to work well for this. I've also tried with a bundle of grass. I can pretty easily get a good alignment by eye, so it seems theoretically doable. Do you have hypotheses around what modifications I could make that would improve alignment in this case?

**Comment by poynting** [comment]
Please provide an example capture and I can take a look.

**Comment by anishau** [comment]
Here you go, thanks! 

[test_grass.zip](https://github.com/micasense/imageprocessing/files/3575358/test_grass.zip)


[test_4rocks.zip](https://github.com/micasense/imageprocessing/files/3575350/test_4rocks.zip)

**Comment by poynting** [comment]
By changing the `pyramid_levels` from `0` to `3` it works fine for both images.  Note that the thermal imagery isn't aligned using any kind of matching -- just using the factory calibration -- so it will be offset slightly, but it doesn't appear to impact the results much given the difference in pixel size.

![image](https://user-images.githubusercontent.com/6610131/64271634-82994100-cef2-11e9-85a9-f1c024d5cfc7.png)

![image](https://user-images.githubusercontent.com/6610131/64271711-a8bee100-cef2-11e9-96bc-540168aebbcf.png)

[Alignment-Rocks.zip](https://github.com/micasense/imageprocessing/files/3575434/Alignment-Rocks.zip)
[Alignment-Grass.zip](https://github.com/micasense/imageprocessing/files/3575435/Alignment-Grass.zip)

**Comment by anishau** [comment]
ah, thank you so much! greatly appreciated the explanation as well.
