### ISSUE TITLE
Sun glint correction on water body

### ISSUE THREAD

**Issue by wondie** [micasense/imageprocessing#74]
Is there any code, or procedure to remove sun glint on water bodies?

**Comment by poynting** [comment]
Sun glint usually results in saturation of the image pixels, so it generally needs to be avoided.

You might try a polarizing filter in front of the lens, but I'm not sure how this will impact the radiometry.  I've also seen people have success flying at lower sun angles on calm(er) days.

**Comment by wondie** [comment]
Thank you for the answer!
