### ISSUE TITLE
Incorrect cropping

### ISSUE THREAD

**Issue by poynting** [micasense/imageprocessing#75]
When installing via a fresh Ananconda install late September 2019, it was noticed that in the alignment and batch processing tutorials the cropping results were incorrect.  Running with an earlier anaconda install worked fine.  The result was slight areas where the overlapping bands were not cropped away.

My guess is that some combination of library versions is causing this. At the least, we need to find the offending library and pin it to a working version; at best, we need to determine the root cause and develop a fix in our code that works across library versions, since the math to compute the crop bands shouldn't be dependent implementations in specific libraries.

Visible as a small red strip on the top and right of this image.
![image](https://user-images.githubusercontent.com/6610131/66245019-04ca8000-e6c0-11e9-9d2d-2fec9d66fda9.png)

**Comment by rrowlands** [comment]
I noticed this as well. It seems like the cropping works for me when I use the alignment tutorial and am displaying the image via a plot, however with the batch tutorial the mismatched red band at the top of the image is much more pronounced.
