### ISSUE TITLE
Correction for DLS1 under overcast conditions

### ISSUE THREAD

**Issue by ComteDeLooz** [micasense/imageprocessing#95]
Hi,

Since the diffuser of DLS1 reflects more light at shallow angles than at steep angles, we need to correct for this. In the module image.py this is done on line 172 (Fresnel correction). An important factor in this multi-layer transmission is the incidence angle (e.g. module dls.py - line 81). For this angle, the sun_sensor_angle is used in the script (module image.py - line 120).

Once the angular correction (Fresnel correction) is applied, a distinction is made between direct sunlight (image.py - line 175) and scattered sunlight (image.py - line 176). The latter is deduced from the first based on the percent_diffuse ratio. This means the scattered sun light is also subjected to the Fresnel correction with the sun_sensor_angle as input. Because the scattered sunlight is originating from different directions, I was wondering if this assumption is correct?

I noticed during drone measurements with the MicaSense RedEdge M in NW-Europe during overcast conditions in autumn / winter times (low solar elevation), the sun_sensor_angle (dls installed vertically upwards) is often relatively high (65° and more). This means the Fresnel corrections applied under these circumstances result in a steep increase of corrected irradiance values. When looking at one flight, high variations are observed that strongly depend on the motion of the drone.

Is it correct to assume under scattered light conditions (cloudy conditions), the sunlight originates from approximately all directions and to apply a kind of average Fresnel correction (not based on sun_sensor_angle) or leave this correction completely out? Or do you have another solution for this?
 
Many thanks in advance!

Kind regards,

CDL

**Comment by poynting** [comment]
Yes, you're correct that the variance in the DLS data increases as the sun-sensor angle increases (sun lower in the sky). Variation in the pose information can increase this variance further.  This is the primary reason MicaSense created DLS2, which actively estimates this angle.
